[package]
name = "pf_tracker_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.4.2"
serde = "1.0.147"
serde_derive = "1.0.147"
chrono = "0.4.23"
